appname: gin-api

env: release
port: 8088

log_file: /data/logs/gin-api/gin-api.log

mysql:
  user: root
  password: root
  host: 127.0.0.1
  port: 3306
  db: test

redis:
  host: 127.0.0.1
  password:
  port: 6379